# This is a basic workflow to help you get started with Actions

name: update mail

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send-mail:
    runs-on: ubuntu-latest
    name: Send email when push on master
    steps:
    
    
      - name: SendGrid Mail Action
        uses: mmichailidis/sendgrid-mail-action@v1.0
        with:
          # The token for sendgrid
          sendgrid-token: '${{ secrets.API_KEY }}'
          # The emails ( can be only one ) that the email will go
          mail: '${{ secrets.MAIL }}'
          # The email that will be shown as sender
          from: '${{ secrets.SENDER }}' # optional, default is sendgridmailaction@github.com
          # The subject of the email
          subject: 'Website update' # optional, default is GitHub action notification
          # Defines if it should be one email with multiple address or multiple emails with a single address
          #individual: 
          # The body of the mail. The placeholders that can be used are $EVENT$, $ISSUE$, $ACTION$
          text: '<body style="margin: 0; padding: 0;"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td style="padding: 10px 0 30px 0;"> <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border: 1px solid #cccccc; border-collapse: collapse;"> <tr> <td align="center" bgcolor="#343a40" style="padding: 40px 0 30px 0; color: #153643; font-size: 28px; font-weight: bold; font-family: Arial, sans-serif;"> <img src="https://imgur.com/0FDeXlF.png" alt="Creating Email Magic" width="300" style="display: block;" /> </td> </tr> <tr> <td bgcolor="#343a40" style="padding: 40px 30px 40px 30px;"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td style="color: white; font-family: Arial, sans-serif; font-size: 24px;"> <b>Hello!</b> </td> </tr> <tr> <td style="padding: 20px 0 30px 0; color: white; font-family: sans-serif; font-size: 16px; line-height: 20px;"> The portfolio was updated today. </td> </tr> <tr> <td align="center"> <a href="https://maelabgrall.github.io/Portfolio/" style="text-decoration: none; color: white; font-family: Arial, sans-serif; font-size: 15px; background-color: #343a40; border: 1px solid #e8dec4; border-radius: 5px; padding: 1% 10% 1%; width: 50%;">Go to the website</a> </td> </tr> </table> </td> </tr> <tr> <td bgcolor="#343a40" style="padding: 30px 30px 30px 30px;"> <hr style="border: 1px solid #e8dec4;"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td style="color: white; font-family: Arial, sans-serif; font-size: 14px;" width="75%"> &copy; Mab photography (meuuul)<br /> Write an email to <a href="mailto:mae.a@outlook.com" style="color: #e8dec4;"> <font color="#e8dec4">mae.a@outlook.com</font> </a> to unsubscribe </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </body>'
