# This is a basic workflow to help you get started with Actions

name: update mail

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send-mail:
    runs-on: ubuntu-latest
    name: Send email when push on master
    steps:
    
    
      - name: SendGrid Mail Action
        uses: mmichailidis/sendgrid-mail-action@v1.0
        with:
          # The token for sendgrid
          sendgrid-token: '${{ secrets.API_KEY }}'
          # The emails ( can be only one ) that the email will go
          mail: '${{ secrets.MAIL }}'
          # The email that will be shown as sender
          from: 'Mab Photography Meuuul' # optional, default is sendgridmailaction@github.com
          # The subject of the email
          subject: 'aeh' # optional, default is GitHub action notification
          # Defines if it should be one email with multiple address or multiple emails with a single address
          #individual: 
          # The body of the mail. The placeholders that can be used are $EVENT$, $ISSUE$, $ACTION$
          text: 'abcd'
